### ISSUE TITLE
What am i supposed to do on "Phone Account might be disabled" ?

### ISSUE THREAD

**Issue by RedVrma** [Konsl/fake-call#1]
When setting up a fake call , It says Phone Account might be disabled.
To use this app you might have to first enable  the corresponding phone account in your phone app.

I am totally lost on what am i supposed to do, i cannot find any phone account in my samsung phone. Please help.

**Comment by Konsl** [comment]
Apparently it's "Calling accounts", I was stupid https://github.com/user-attachments/assets/c2db7f56-bb73-40ab-a352-b7adc2094c66
